apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-consumer
  labels:
    app: my-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-consumer
  template:
    metadata:
      labels:
        app: my-consumer
    spec:
      containers:
        - name: my-consumer
          image: my-consumer:0.1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BROKERS
              value: "redpanda.default.svc.cluster.local:9092"
            - name: MONGOURI
              value: "mongodb+srv://root:password@my-mongodb.default.svc.cluster.local/messages_db?authSource=admin&tls=false"
